# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pi Videogame Programming Blog
author:
  name: Saúl Blanco Villorejo
  email: saul101.pi@outlook.com
email: saul101.pi@outlook.com
description: >-
  Blog in which I post the videogame projects I'm working in
  and my thought process while making them.
baseurl: "" # /blog
domain: "pi101s.github.io"
url: "https://pi101s.github.io" # http://example.com
twitter_username: saulbv101

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Pagination settings
paginate_path: /posts/:num
paginate: 5

# Archives settings
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "post/:title.html"

# Generate social links in footer.
social_links:
  - { platform: github,         user_url: "https://github.com/pi101s" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/saulbv/" }
  - { platform: twitter,        user_url: "https://twitter.com/saulbv101" }